#!/usr/bin/env bash

# Build the docs.
doxygen

# Run the coverage report and push to codecov.
python3 -m coverxygen \
  --xml-dir xml/ \
  --src-dir ../src \
  --output doc-coverage.info \
  --kind class \
  --scope public
bash <(curl -s https://codecov.io/bash) \
  -f doc-coverage.info \
  -F doccoverage || 
  echo "Codecov did not collect coverage reports"

# Badges and flags are flaky in codecov. Let's dump some json and 
# let shields build our badge. 
python3 -m coverxygen \
  --xml-dir xml/ \
  --src-dir ../src \
  --output - \
  --format json-summary \
  --kind class \
  --scope public | 
  jq '{"schemaVersion": 1,  "label": "doxygen","color":"informational","message": "\((.total.coverage_rate*100 | floor))%"}' > html/doccoverage.json
